// Iconos comunes para la aplicación - compatibilidad con Heroicons v2
import {
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowTrendingUpIcon,
  ArrowPathIcon,
  CurrencyEuroIcon,
  ChartBarIcon,
  BanknotesIcon,
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  ChartPieIcon,
  CogIcon,
  CheckCircleIcon,
  XCircleIcon,
  MagnifyingGlassIcon,
  HomeIcon,
  DocumentChartBarIcon,
  Bars3Icon,
  XMarkIcon,
  LightBulbIcon,
  GlobeAltIcon,
  BuildingOfficeIcon,
  CurrencyDollarIcon,
  MapPinIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  InformationCircleIcon
} from '@heroicons/react/24/outline';

// Exportar iconos con nombres consistentes
export {
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowTrendingUpIcon as TrendingUpIcon, // Alias para compatibilidad
  ArrowTrendingUpIcon,
  ArrowPathIcon,
  CurrencyEuroIcon,
  ChartBarIcon,
  BanknotesIcon,
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  ChartPieIcon,
  CogIcon,
  CheckCircleIcon,
  XCircleIcon,
  MagnifyingGlassIcon,
  HomeIcon,
  DocumentChartBarIcon,
  Bars3Icon,
  XMarkIcon,
  LightBulbIcon,
  GlobeAltIcon,
  BuildingOfficeIcon,
  CurrencyDollarIcon,
  MapPinIcon,
  ArrowPathIcon as RefreshIcon, // Alias para refresh
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  InformationCircleIcon
};
